<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            'Albanija',
            'Alžir',
            'Andora',
            'Angola',
            'Antigva i Barbuda',
            'Argentina',
            'Armenija',
            'Australija',
            'Austrija',
            'Azerbajdžan',
            'Bahami',
            'Bahrein',
            'Bangladeš',
            'Barbados',
            'Belgija',
            'Belize',
            'Benin',
            'Butan',
            'Bolivija',
            'Bosna i Hercegovina',
            'Bocvana',
            'Brazil',
            'Brunej',
            'Bugarska',
            'Burkina Faso',
            'Burundi',
            'Kambodža',
            'Kamerun',
            'Kanada',
            'Zelenortska Republika',
            'Srednjoafrička Republika',
            'Čile',
            'Kina',
            'Kolumbija',
            'Komori',
            'Kongo (Republika)',
            'Kostarika',
            'Hrvatska',
            'Cipar',
            'Češka',
            'Danska',
            'Džibuti',
            'Dominika',
            'Dominikanska Republika',
            'Istočni Timor',
            'Ekvador',
            'Egipat',
            'Salvador',
            'Estonija',
            'Esvatini',
            'Etiopija',
            'Fidži',
            'Finska',
            'Francuska',
            'Gabon',
            'Gambija',
            'Gruzija',
            'Njemačka',
            'Gana',
            'Grčka',
            'Grenada',
            'Gvatemala',
            'Gvineja',
            'Gvineja Bisau',
            'Gvajana',
            'Honduras',
            'Hong Kong',
            'Mađarska',
            'Island',
            'Indija',
            'Indonezija',
            'Irak',
            'Irska',
            'Izrael',
            'Italija',
            'Jamajka',
            'Japan',
            'Jordan',
            'Kazahstan',
            'Kenija',
            'Kiribati',
            'Kosovo',
            'Kuvajt',
            'Kirgistan',
            'Laos',
            'Latvija',
            'Libanon',
            'Lesoto',
            'Liberija',
            'Lihtenštajn',
            'Litva',
            'Luksemburg',
            'Madagaskar',
            'Malavi',
            'Malezija',
            'Maldivi',
            'Mali',
            'Malta',
            'Maršalovi Otoci',
            'Mauritanija',
            'Mauricijus',
            'Meksiko',
            'Mikronezija',
            'Moldavija',
            'Monako',
            'Mongolija',
            'Crna Gora',
            'Maroko',
            'Mozambik',
            'Namibija',
            'Nauru',
            'Nepal',
            'Nizozemska',
            'Novi Zeland',
            'Niger',
            'Sjeverna Makedonija',
            'Norveška',
            'Oman',
            'Palau',
            'Panama',
            'Papua Nova Gvineja',
            'Paragvaj',
            'Peru',
            'Filipini',
            'Poljska',
            'Portugal',
            'Katar',
            'Rumunjska',
            'Ruanda',
            'Sveti Kristofor i Nevis',
            'Sveta Lucija',
            'Sveti Vincent i Grenadini',
            'Samoa',
            'San Marino',
            'Sveti Toma i Princip',
            'Saudijska Arabija',
            'Senegal',
            'Srbija',
            'Sejšeli',
            'Sijera Leone',
            'Singapur',
            'Slovačka',
            'Slovenija',
            'Solomonski Otoci',
            'Južnoafrička Republika',
            'Južna Koreja',
            'Španjolska',
            'Šri Lanka',
            'Surinam',
            'Švedska',
            'Švicarska',
            'Tajvan',
            'Tadžikistan',
            'Tanzanija',
            'Tajland',
            'Togo',
            'Tonga',
            'Trinidad i Tobago',
            'Tunis',
            'Turska',
            'Turkmenistan',
            'Tuvalu',
            'Uganda',
            'Ujedinjeni Arapski Emirati',
            'Ujedinjeno Kraljevstvo',
            'Sjedinjene Američke Države',
            'Urugvaj',
            'Uzbekistan',
            'Vanuatu',
            'Vijetnam',
            'Zambija',
            'Zimbabve'
        ];



        foreach ($countries as $name) {
            Country::firstOrCreate(['name' => $name]);
        }
    }
}
